package cic

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/jung-kurt/gofpdf"
	"github.com/das-rebel/finwipe/internal/config"
)

// CIBIL dispute form generator
// Users must SUBMIT THESE MANUALLY at cibil.com/dispute

type Bureau string

const (
	CIBIL   Bureau = "CIBIL"
	EXPERIAN       = "Experian"
	EQUIFAX        = "Equifax"
	CRIF           = "CRIF High Mark"
)

type Entry struct {
	Type        string // account | enquiry | personal_info
	Description string
	NBFCName    string
	ControlNo   string // CIBIL control number
}

type Generator struct {
	outputDir string
}

func New(outputDir string) *Generator {
	os.MkdirAll(outputDir, 0755)
	return &Generator{outputDir: outputDir}
}

func (g *Generator) Generate(bureau Bureau, profile config.Profile, entries []Entry) (string, error) {
	filename := filepath.Join(g.outputDir, fmt.Sprintf("cic_dispute_%s_%s.pdf",
		bureau, time.Now().Format("2006-01-02")))

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	pdf.SetFont("Arial", "B", 14)
	pdf.CellFormat(0, 8, fmt.Sprintf("%s Dispute Form", bureau), "", 1, "C", false, 0, "")
	pdf.SetFont("Arial", "I", 9)
	pdf.CellFormat(0, 5, "Submit online at: cibil.com/dispute | Generated by FinWipe", "", 1, "C", false, 0, "")
	pdf.Ln(5)

	// Consumer Details
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "SECTION 1: CONSUMER DETAILS", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)

	fields := []struct {
		label, value string
	}{
		{"Full Name:", profile.Name},
		{"Email:", profile.Email},
		{"Phone:", profile.Phone},
		{"Address:", profile.Address},
		{"Date of Birth:", ""},
		{"PAN:", ""},
		{"Date:", time.Now().Format("02 January 2006")},
	}

	for _, f := range fields {
		pdf.CellFormat(50, 6, f.label, "", 0, "", false, 0, "")
		pdf.CellFormat(0, 6, f.value, "", 1, "", false, 0, "")
	}
	pdf.Ln(3)

	// Dispute Details
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "SECTION 2: DISPUTED ENTRIES", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.Ln(2)

	for i, e := range entries {
		pdf.SetFont("Arial", "B", 10)
		pdf.CellFormat(0, 6, fmt.Sprintf("Entry %d:", i+1), "", 1, "", false, 0, "")
		pdf.SetFont("Arial", "", 10)
		pdf.MultiCell(0, 5, fmt.Sprintf("Type: %s\nDescription: %s\nInstitution: %s\nControl Number: %s",
			e.Type, e.Description, e.NBFCName, e.ControlNo), "", "L", false)
		pdf.Ln(2)
	}

	// Instructions
	pdf.Ln(3)
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "SECTION 3: HOW TO SUBMIT", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	instructions := fmt.Sprintf(`Step 1: Visit %s
Step 2: Login to your account or use the dispute form
Step 3: Select the entries listed above as "Disputed"
Step 4: Attach this completed form as proof
Step 5: Submit and note the reference number

Timeline: %s should process as soon as reasonable (Section 8(6), DPDP Act 2023.
You will receive email updates every 7 days.
If unresolved, escalate to:
  - RBI Integrated Ombudsman Scheme (RB-IOS): rbi.org.in
  - Data Protection Board of India
  - Consumer Forum under CPA 2019`, bureau, bureau)
	pdf.MultiCell(0, 5, instructions, "", "L", false)
	pdf.Ln(3)

	// Signature
	pdf.SetFont("Arial", "B", 10)
	pdf.CellFormat(0, 6, "SECTION 4: DECLARATION", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.MultiCell(0, 5, "I declare that the information provided above is true and accurate to the best of my knowledge. I authorize the erasure of the disputed data elements from my credit information record maintained by "+string(bureau)+".", "", "L", false)
	pdf.Ln(5)

	pdf.CellFormat(50, 6, "Signature:", "", 0, "", false, 0, "")
	pdf.CellFormat(0, 6, profile.Name, "B", 1, "", false, 0, "")
	pdf.Ln(3)
	pdf.CellFormat(50, 6, "Date:", "", 0, "", false, 0, "")
	pdf.CellFormat(0, 6, time.Now().Format("02 January 2006"), "B", 1, "", false, 0, "")

	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 8)
	pdf.CellFormat(0, 4, "Generated by FinWipe | github.com/das-rebel/finwipe | This form is a guide only. Verify details at "+string(bureau)+".com", "", 1, "C", false, 0, "")

	if err := pdf.OutputFileAndClose(filename); err != nil {
		return "", err
	}

	return filename, nil
}
