package letter

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/jung-kurt/gofpdf"
	"github.com/das-rebel/finwipe/internal/config"
	"github.com/das-rebel/finwipe/internal/nbfc"
)

type Generator struct {
	outputDir string
}

func New(outputDir string) *Generator {
	os.MkdirAll(outputDir, 0755)
	return &Generator{outputDir: outputDir}
}

func (g *Generator) Generate(n nbfc.Entity, profile config.Profile) (string, error) {
	filename := filepath.Join(g.outputDir, fmt.Sprintf("deletion_letter_%s_%s.pdf",
		n.ID, time.Now().Format("2006-01-02")))

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Header
	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(0, 8, "DATA DELETION REQUEST", "", 1, "C", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(0, 5, "Pursuant to Section 8(6) of the DPDP Act, 2023 and Rule 8 of the DPDP Rules, 2025", "", 1, "C", false, 0, "")
	pdf.Ln(5)

	// From/To
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "From:", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 11)
	pdf.MultiCell(0, 5, fmt.Sprintf("%s\n%s\nEmail: %s\nPhone: %s", profile.Name, profile.Address, profile.Email, profile.Phone), "", "L", false)
	pdf.Ln(3)

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "To:", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 11)
	pdf.MultiCell(0, 5, fmt.Sprintf("%s\nGrievance Officer\n%s\nEmail: %s", n.Name, n.Address, n.GrievanceEmail), "", "L", false)
	pdf.Ln(5)

	pdf.SetFont("Arial", "", 11)
	pdf.CellFormat(0, 6, fmt.Sprintf("Date: %s", time.Now().Format("02 January 2006")), "", 1, "", false, 0, "")
	pdf.Ln(3)

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "Subject: Request for Erasure of Personal Data under Section 8(6), DPDP Act 2023", "", 1, "", false, 0, "")
	pdf.Ln(3)

	pdf.SetFont("Arial", "", 11)
	body := fmt.Sprintf(`Dear Grievance Officer,

I, %s, am exercising my right to erasure of personal data under Section 8(6) of the Digital Personal Data Protection Act, 2023 (DPDP Act) and Rule 8 of the DPDP Rules, 2025.

The purpose for which my personal data was collected by %s is no longer being served. I hereby request deletion of the following categories of personal data held by %s:

  □ Marketing and promotional data
  □ Third-party shared data
  □ Behavioral/usage data collected through your digital lending app or website
  □ Pre-approved loan offer profiles
  □ Call recordings and customer service interaction logs
  □ Device fingerprint and metadata data

I request acknowledgment of this request within 48 hours as mandated by Rule 8(3) of the DPDP Rules, 2025, and completion of deletion within 30 days of this notice.

This request does not extend to personal data whose retention is required by or under any law for the time being in force, including but not limited to the RBI Act, Companies Act, and Income Tax Act. Specifically, this request does not seek deletion of:
  □ KYC documents and identity records
  □ Transaction and loan account records
  □ Records required for ongoing loan servicing
  □ Regulatory reporting records

In accordance with Rule 8(5) of the DPDP Rules, 2025, please confirm in writing the categories of data deleted and the manner of deletion.

If no response is received within 30 days, I reserve the right to escalate this matter to the Data Protection Board of India and the Reserve Bank of India.

For any communication regarding this request:
  Email: %s
  Phone: %s

Regards,
%s
%s`, profile.Name, n.Name, n.Name, profile.Email, profile.Phone, profile.Name, profile.Address)

	pdf.MultiCell(0, 6, body, "", "L", false)

	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 9)
	pdf.CellFormat(0, 5, "This letter was generated by FinWipe (github.com/das-rebel/finwipe)", "", 1, "C", false, 0, "")

	if err := pdf.OutputFileAndClose(filename); err != nil {
		return "", err
	}

	return filename, nil
}

func (g *Generator) GenerateAll(nbfcs []nbfc.Entity, profile config.Profile) (generated int, failed []string) {
	for _, n := range nbfcs {
		if n.Address == "" {
			n.Address = "[Address on file with " + n.Name + "]"
		}
		_, err := g.Generate(n, profile)
		if err != nil {
			failed = append(failed, fmt.Sprintf("%s: %v", n.ID, err))
		} else {
			generated++
		}
	}
	return
}

// GenerateRBIComplaint generates a pre-filled RBI Ombudsman complaint (Form-IV equivalent)
// for cases where NBFC failed to acknowledge or act on the deletion request.
// Outputs both a PDF letter and an email body for crpc@rbi.org.in.
func (g *Generator) GenerateRBIComplaint(reqID string, entity nbfc.Entity, profile config.Profile, reqAgeDays int) (pdfPath string, emailBody string, err error) {
	filename := filepath.Join(g.outputDir, fmt.Sprintf("rbi_complaint_%s_%s.pdf",
		entity.ID, time.Now().Format("2006-01-02")))

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// RBI Ombudsman header
	pdf.SetFont("Arial", "B", 14)
	pdf.CellFormat(0, 8, "RESERVE BANK OF INDIA — INTEGRATED OMBUDSMAN SCHEME", "", 1, "C", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(0, 5, "Complaint under Section 18 of the RBl Act, 1934 / Form-IV / Online: https://rbis.rbi.org.in", "", 1, "C", false, 0, "")
	pdf.Ln(8)

	// Complainant details
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "1. COMPLAINANT DETAILS", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.MultiCell(0, 5, fmt.Sprintf("Name: %s\nAddress: %s\nEmail: %s\nPhone: %s\nDPR Reference: %s", profile.Name, profile.Address, profile.Email, profile.Phone, reqID), "", "L", false)
	pdf.Ln(3)

	// Respondent details
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "2. RESPONDENT (NBFC / DATA FIDUCIARY)", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.MultiCell(0, 5, fmt.Sprintf("Name: %s\nGrievance Officer Email: %s\nCategory: %s", entity.Name, entity.GrievanceEmail, entity.Category), "", "L", false)
	pdf.Ln(3)

	// Complaint details
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "3. NATURE OF COMPLAINT", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.MultiCell(0, 5, fmt.Sprintf("Category: Non-compliance with DPDPA 2023 / Data Protection\nSub-category: Failure to honor data deletion request under Section 8(6), DPDP Act 2023\nDate of Request: %s\nDays Elapsed: %d days\nAcknowledgment Received: No\nResponse / Deletion Received: No", time.Now().AddDate(0, 0, -reqAgeDays).Format("02 January 2006"), reqAgeDays), "", "L", false)
	pdf.Ln(3)

	// Facts
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "4. FACTS OF THE CASE", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	body := fmt.Sprintf(`I submitted a formal data deletion request to %s on %s (Ref: %s) pursuant to Section 8(6) of the Digital Personal Data Protection Act, 2023 and Rule 8 of the DPDP Rules, 2025.

The NBFC was given 30 days to:
  a) Acknowledge receipt of the request, and
  b) Complete deletion of personal data categories listed in my request.

To date (%d days elapsed), %s has:
  ❌ Failed to acknowledge the request (as required by Rule 8(3))
  ❌ Failed to respond to the deletion request
  ❌ Failed to provide confirmation of data deletion (as required by Rule 8(5))

I have exhausted the Grievance Redressal Mechanism of the NBFC and have not received a satisfactory resolution.

Relevant correspondence: All communications sent to %s (Grievance Officer).
The request was tracked under DPR-ID: %s`, entity.Name, time.Now().AddDate(0, 0, -reqAgeDays).Format("02 January 2006"), reqID, reqAgeDays, entity.Name, entity.GrievanceEmail, reqID)
	pdf.MultiCell(0, 5, body, "", "L", false)
	pdf.Ln(3)

	// Relief sought
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "5. RELIEF SOUGHT", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.MultiCell(0, 5, fmt.Sprintf(`a) Direction to %s to acknowledge the data deletion request,
b) Direction to %s to complete deletion of personal data categories listed in my original request,
c) Confirmation in writing of the categories deleted and the manner of deletion,
d) Any other relief the Hon'ble Ombudsman deems fit to grant.`, entity.Name, entity.Name), "", "L", false)
	pdf.Ln(3)

	// Declaration
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "6. DECLARATION", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.MultiCell(0, 5, "I declare that the above facts are true and correct to the best of my knowledge. I have not filed any other complaint or suit before any court/authority regarding the same subject matter.", "", "L", false)
	pdf.Ln(5)

	// Signature
	pdf.CellFormat(0, 6, fmt.Sprintf("Date: %s", time.Now().Format("02 January 2006")), "", 1, "", false, 0, "")
	pdf.Ln(5)
	pdf.CellFormat(0, 6, "Signature: ___________________________", "", 1, "", false, 0, "")
	pdf.Ln(3)
	pdf.CellFormat(0, 6, fmt.Sprintf("Name: %s", profile.Name), "", 1, "", false, 0, "")

	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 8)
	pdf.CellFormat(0, 4, "Generated by FinWipe | rbi.org.in/Secure/OnlineRBI Ombudsman | Email: crpc@rbi.org.in | Phone: 14448 (toll-free)", "", 1, "C", false, 0, "")

	if err := pdf.OutputFileAndClose(filename); err != nil {
		return "", "", err
	}

	// Build email body
	emailBody = fmt.Sprintf(`To: crpc@rbi.org.in
Subject: Complaint — %s — Non-compliance with DPDPA 2023 Data Deletion Request (Ref: %s)

Dear Sir/Madam,

I wish to file a complaint under the Reserve Bank of India — Integrated Ombudsman Scheme, 2021, against %s (NBFC Reg. No.: %s) for non-compliance with my data deletion request under Section 8(6) of the Digital Personal Data Protection Act, 2023.

COMPLAINANT: %s | %s | %s

RESPONDENT: %s | Grievance Email: %s

FACTS:
- Submitted data deletion request on: %s (Ref: %s)
- Days elapsed without acknowledgment: %d
- Acknowledgment received: NO
- Deletion confirmed: NO
- Grievance mechanism exhausted: YES

I request your kind intervention to direct the NBFC to:
1. Acknowledge the data deletion request immediately
2. Complete deletion of personal data categories in my original request
3. Provide written confirmation of deletion as mandated by Rule 8(5), DPDP Rules, 2025

A detailed complaint letter is attached (PDF) for your reference.

I request the Hon'ble Ombudsman to take suo motu cognizance and initiate action under Section 18 of the RBI Act, 1934.

Thanking you,
%s (%s)
Email: %s | Phone: %s

---
Ref DPR-ID: %s
This complaint was generated using FinWipe (github.com/das-rebel/finwipe)`,

		entity.Name, reqID,
		entity.Name, entity.ShortName,
		profile.Name, profile.Email, profile.Phone,
		entity.Name, entity.GrievanceEmail,
		time.Now().AddDate(0, 0, -reqAgeDays).Format("02 January 2006"), reqID, reqAgeDays,
		profile.Name, profile.Name, profile.Email, profile.Phone,
		reqID)

	return filename, emailBody, nil
}
