package letter

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/jung-kurt/gofpdf"
	"github.com/das-rebel/finwipe/internal/config"
	"github.com/das-rebel/finwipe/internal/nbfc"
)

type Generator struct {
	outputDir string
}

func New(outputDir string) *Generator {
	os.MkdirAll(outputDir, 0755)
	return &Generator{outputDir: outputDir}
}

func (g *Generator) Generate(n nbfc.Entity, profile config.Profile) (string, error) {
	filename := filepath.Join(g.outputDir, fmt.Sprintf("deletion_letter_%s_%s.pdf",
		n.ID, time.Now().Format("2006-01-02")))

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Header
	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(0, 8, "DATA DELETION REQUEST", "", 1, "C", false, 0, "")
	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(0, 5, "Pursuant to Section 8(6) of the DPDP Act, 2023 and Rule 8 of the DPDP Rules, 2025", "", 1, "C", false, 0, "")
	pdf.Ln(5)

	// From/To
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "From:", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 11)
	pdf.MultiCell(0, 5, fmt.Sprintf("%s\n%s\nEmail: %s\nPhone: %s", profile.Name, profile.Address, profile.Email, profile.Phone), "", "L", false)
	pdf.Ln(3)

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "To:", "", 1, "", false, 0, "")
	pdf.SetFont("Arial", "", 11)
	pdf.MultiCell(0, 5, fmt.Sprintf("%s\nGrievance Officer\n%s\nEmail: %s", n.Name, n.Address, n.GrievanceEmail), "", "L", false)
	pdf.Ln(5)

	pdf.SetFont("Arial", "", 11)
	pdf.CellFormat(0, 6, fmt.Sprintf("Date: %s", time.Now().Format("02 January 2006")), "", 1, "", false, 0, "")
	pdf.Ln(3)

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 6, "Subject: Request for Erasure of Personal Data under Section 8(6), DPDP Act 2023", "", 1, "", false, 0, "")
	pdf.Ln(3)

	pdf.SetFont("Arial", "", 11)
	body := fmt.Sprintf(`Dear Grievance Officer,

I, %s, am exercising my right to erasure of personal data under Section 8(6) of the Digital Personal Data Protection Act, 2023 (DPDP Act) and Rule 8 of the DPDP Rules, 2025.

The purpose for which my personal data was collected by %s is no longer being served. I hereby request deletion of the following categories of personal data held by %s:

  □ Marketing and promotional data
  □ Third-party shared data
  □ Behavioral/usage data collected through your digital lending app or website
  □ Pre-approved loan offer profiles
  □ Call recordings and customer service interaction logs
  □ Device fingerprint and metadata data

I request acknowledgment of this request within 48 hours as mandated by Rule 8(3) of the DPDP Rules, 2025, and completion of deletion within 30 days of this notice.

This request does not extend to personal data whose retention is required by or under any law for the time being in force, including but not limited to the RBI Act, Companies Act, and Income Tax Act. Specifically, this request does not seek deletion of:
  □ KYC documents and identity records
  □ Transaction and loan account records
  □ Records required for ongoing loan servicing
  □ Regulatory reporting records

In accordance with Rule 8(5) of the DPDP Rules, 2025, please confirm in writing the categories of data deleted and the manner of deletion.

If no response is received within 30 days, I reserve the right to escalate this matter to the Data Protection Board of India and the Reserve Bank of India.

For any communication regarding this request:
  Email: %s
  Phone: %s

Regards,
%s
%s`, profile.Name, n.Name, n.Name, profile.Email, profile.Phone, profile.Name, profile.Address)

	pdf.MultiCell(0, 6, body, "", "L", false)

	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 9)
	pdf.CellFormat(0, 5, "This letter was generated by FinWipe (github.com/das-rebel/finwipe)", "", 1, "C", false, 0, "")

	if err := pdf.OutputFileAndClose(filename); err != nil {
		return "", err
	}

	return filename, nil
}

func (g *Generator) GenerateAll(nbfcs []nbfc.Entity, profile config.Profile) (generated int, failed []string) {
	for _, n := range nbfcs {
		if n.Address == "" {
			n.Address = "[Address on file with " + n.Name + "]"
		}
		_, err := g.Generate(n, profile)
		if err != nil {
			failed = append(failed, fmt.Sprintf("%s: %v", n.ID, err))
		} else {
			generated++
		}
	}
	return
}
